component: Add com.android.location.provider to PRODUCT_BOOT_JARS
This patch adds com.android.location.provider to PRODUCT_BOOT_JARS to fix below
runtime error when quickboot is applied.

I art     : Rejecting re-init on previously-failed class java.lang.Class<com.android.location.fused.FusedLocationProvider>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/location/provider/LocationProviderBase;
I art     :   at android.os.IBinder com.android.location.fused.FusedLocationService.onBind(android.content.Intent) (FusedLocationService.java:29)
I art     :   at void android.app.ActivityThread.handleBindService(android.app.ActivityThread$BindServiceData) (ActivityThread.java:3219)
I art     :   at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$BindServiceData) (ActivityThread.java:-1)
I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1573)
I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I art     :   at void android.os.Looper.loop() (Looper.java:154)
I art     :   at void com.android.server.SystemServer.startOtherServices() (SystemServer.java:635)
I art     :   at void com.android.server.SystemServer.run() (SystemServer.java:217)
I art     :   at void com.android.server.SystemServer.main(java.lang.String[]) (SystemServer.java:143)
I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:905)
I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:795)
I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.location.provider.LocationProviderBase" on path: DexPathList[[zip file "/system/priv-app/FusedLocation/FusedLocation.apk"],nativeLibraryDirectories=[/system/priv-app/FusedLocation/lib/arm, /system/lib, /vendor/lib, /system/lib, /vendor/lib]]
I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I art     :   at android.os.IBinder com.android.location.fused.FusedLocationService.onBind(android.content.Intent) (FusedLocationService.java:29)
I art     :   at void android.app.ActivityThread.handleBindService(android.app.ActivityThread$BindServiceData) (ActivityThread.java:3219)
I art     :   at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$BindServiceData) (ActivityThread.java:-1)
I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1573)
I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I art     :   at void android.os.Looper.loop() (Looper.java:154)
I art     :   at void com.android.server.SystemServer.startOtherServices() (SystemServer.java:635)
I art     :   at void com.android.server.SystemServer.run() (SystemServer.java:217)
I art     :   at void com.android.server.SystemServer.main(java.lang.String[]) (SystemServer.java:143)
I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:905)
I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:795)
I art     :
D AndroidRuntime: Shutting down VM

Signed-off-by: Sungwoo Park <swpark@nexell.co.kr>